### ISSUE TITLE
Allow download of pre-release version

### ISSUE THREAD

**Issue by roboter5123** [NewAmazingPVP/AutoUpdatePlugins#18]
A way to download pre-release versions from github would allow for getting in development versions of plugins automaticly

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the handleGitHubDownload method to allow downloading pre-release versions from GitHub. Added a new parameter to specify whether to download pre-release versions or not.

You can review changes in this commit: https://github.com/lattaai12/NewAmazingPVP-AutoUpdatePlugins-18/commit/eb3cc5cc38066e77d3e19c8f1297da9f5796c85a.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by NewAmazingPVP** [comment]
Sounds good. I will implement it soon when I get time. On the TODO list!

**Comment by NewAmazingPVP** [comment]
@roboter5123 Please go ahead and try this [build](https://cdn.discordapp.com/attachments/1103725182314614834/1311537178618105876/autoupdateplugins-preReleasesSupport.jar?ex=674937ae&is=6747e62e&hm=fa6c9737ea4ebbf81fcfb465b1df86a3f2ff43f7a5f4653918cd06b2f76dcb8d&), and let me know if this works as intended.

**Comment by NewAmazingPVP** [comment]
Hey there, I have released the [new version](https://github.com/NewAmazingPVP/AutoUpdatePlugins/releases/download/v10.5/autoupdateplugins-10.5.jar) with this feature implemented. Please let me know if any issues arise.
