### ISSUE TITLE
Some enhancements could be made

### ISSUE THREAD

**Issue by RadND** [NewAmazingPVP/AutoUpdatePlugins#4]
Good plugin. If I had known about this one earlier, maybe I wouldn't have to write and duplicate and run some plugin-downloading script myself.

Do you accept PR ? Do you accept PR in gplv3 license (just asking)?

### Some enhancements could be made :

there are some plugins only hosted compiled jar file on modrith ( E.g. Dynmap ) , bukkit ( worldguard ) , and maybe hangar. these two don't updated too often, though.

jenkins have there own api , curently not used .  FAWE 's jenkins  not work in my test might because of this.

spiget and github ask for a custom User-Agent, which curently didn't set

mutiple artifacts : EssentialsX 's github realease have a lot artifacts , need a way to specify which is which

some plugin can update by themselves, E.g. skinrestorer ,so they can be acquired for first time and then  leave it be.

### Some hard one:

why use stdout rather than plugin logger ? (I don't know how to support different platform ,though)

version problem . often happen with NMS plugin  E.g  when sometimes newer MC version cameout, protocolLib don't have stable release for second-newest MC version provided on spigot 
it;s jenkins have this version of plugin, but newest dev build is for the newest MC version .update will result in chaos
so these kind of plugin could use an option to only update with manually command/confirm

**Comment by NewAmazingPVP** [comment]
Go ahead with your PR :)

This was one of my first few plugins that I made during my free time, and I did go with the Jenkins REST API to retrieve the latest build of the project. It's weird why FAWE Jenkins doesn't work, though...

I did want to add support for modrinth and bukkit but never got time to do so. I would appreciate it if someone in the community was willing to step up.

It seems like you are right; there is no custom user agent header, and should add one.

Multiple artifacts are indeed a hassle, and I never really worked on them because I never had the time. Again, I would appreciate the PR from anyone, though.

Plugins that auto-update can be left alone, yes.

I used stout mostly so that it works on all platforms with one line instead of making it for every platform (bungeecord, spigot, and especially velocity have different ways to do it).

Yeah, I agree with protocolLib; it's a hassle and breaks every version change and should either be updated manually or with safety checks.

**Comment by NewAmazingPVP** [comment]
@RadND Please check out the latest release:
I have added the custom user agents
Also added dev.bukkit.org support
Fixed jenkins not working for certain projects (so it should now work for FAWE and everything else)
Config.yml clarification, etc.
