### ISSUE TITLE
Don't update plugins on server startup

### ISSUE THREAD

**Issue by Josh65-2201** [NewAmazingPVP/AutoUpdatePlugins#6]
An addition to #5. Updates should not be done on server start as that requires another restart to apply, It also breaks plugins as the file gets changes after it loaded.

Ideally instead of an timer to download them it should be check on system time set in the config (0 = mid-night server time, 12 = mid-day server time), then restart the server with a configurable time after there done downloading with notice.

**Comment by NewAmazingPVP** [comment]
I can add a feature to disable plugin updates on startup

**Comment by NewAmazingPVP** [comment]
Sorry for not replying been busy with other projects

**Comment by NewAmazingPVP** [comment]
Hey, btw, @Josh65-2201 Have you tried adjusting this setting? Just curious ![image](https://github.com/NewAmazingPVP/AutoUpdatePlugins/assets/87737759/4fa0fb10-b440-4d4a-8a8d-8315688972f7)I haven't touched on this plugin in a while, and since I'm free, I'm deciding to add more features. The problem you seem to have suggested here can be potentially fixed by increasing the time of that setting.

**Comment by Josh65-2201** [comment]
Yes since there wasn't a update command before it wasn't very easy to get it aligned with the restart time of the server. I can now just set it to infinite practically.

**Comment by NewAmazingPVP** [comment]
Sounds good
