### ISSUE TITLE
Jenkins/Github multiple downloads problem

### ISSUE THREAD

**Issue by Kaerix** [NewAmazingPVP/AutoUpdatePlugins#9]
Hi, I'm having an issue downloading each EssentialsX plugin straight from Jenkins, because of the fact that your plugin only seems to support downloading the first jar available, so for example:

Downloading EssentialsX from Jenkins, it only always downloads the first jar and I'm unable to automatically download EssentialsXChat/Discord/Spawn

Downloading AuthMeReloaded from Jenkins, it downloads the first jar, which on the site is actually the javadoc jar, which is not even the plugin.

Please, if it's possible, add support to search a specific jar name or use custom links from where the plugin should download (by that I mean like searching EssentialsX-*.jar or EssentialsXChat-*.jar on Jenkins and have the plugin download the first jar it sees)

Thank you so much for your plugin as it works perfectly except for this small issue 😊

**Comment by NewAmazingPVP** [comment]
Thank you for your kind words! And sorry for not replying, as I have been a bit busy lately. Multiple artifacts are an interesting issue to implement as to how to let people choose which artifacts or jars to download. I'll look into adding this feature and fixing AutoMeReloaded Jenkins, and I will let you know why I do it!.

**Comment by NewAmazingPVP** [comment]
Hey, I am so sorry for not working on this. I have very bad time management and almost forgot about this so sorry. Since I have some free time now, I have made a [beta build](https://cdn.discordapp.com/attachments/1103725182314614834/1249487086143410229/autoupdateplugins-bugFixes.jar?ex=66677b07&is=66662987&hm=f07aa95274437f8017ef643063cc2e0a51838813a2eb06c78e375003f8cfdbc5&) that would fix the AuthMeReloaded Jenkins while I am working on implementing multiple artifacts. It would be great if you could test it out and let me know if it works as intended.

**Comment by NewAmazingPVP** [comment]
@Kaerix

**Comment by NewAmazingPVP** [comment]
Hey @Kaerix I have now also added multi-artifact support in this [build] (https://cdn.discordapp.com/attachments/1103725182314614834/1249880259411841117/autoupdateplugins-7.0.jar?ex=6668e933&is=666797b3&hm=92ecbe7e307aba3a20432e3a9b806dcd983eb7f79bf1a53fc6e657e085868eaa&). For example, if you want essentials chat, you can do
`ymlEssentialsXChat: https://github.com/EssentialsX/Essentialsmulti[3]`Since its 3rd artifact in the release ![image](https://github.com/NewAmazingPVP/AutoUpdatePlugins/assets/87737759/e62b6fd0-491a-4846-b1a5-3cc6264c7a5d)So basically, for any multi-artifact plugins on github, paste their normal link and add multi[num], where num is the artifact number. So for essentials chat, it would be: https://github.com/EssentialsX/Essentials + multi[3] = https://github.com/EssentialsX/Essentialsmulti[3].

**Comment by NewAmazingPVP** [comment]
Let me know if you want me to add anything else! This is implemented in the new released version.

**Comment by Kaerix** [comment]
Wonderful, thank you so much! Will test later today

**Comment by NewAmazingPVP** [comment]
Hey @Kaerix So the AuthMeReloaded is already fixed because in code I have made it so that it automatically ignores sources/legacy/javadoc jars and downloads the right one. Though I do see how having a multiartifacts option in there might potentially helpful for other Jenkins. Are you aware of any other Jenkins that have multiple actual plugin jars, such as Essentials? By the way, instead of multi[num], I will just make it so that you only have to put [num] at the end.

**Comment by Kaerix** [comment]
Oh, okay! There is also https://ci.lucko.me/job/spark/
For me, EssentialsX jenkins multi downloads would be _essential_ for my server to work, as the only versions that support 1.20.6 are the dev versions, most easily downloaded from their Jenkins page

**Comment by NewAmazingPVP** [comment]
Thank you for linking me to these jenkins. I see now why multi artifacts would be useful for jenkins as well. Here so I'll do this, to avoid confusion I'll remove auto checks for javadocs/sources/etc jar, but users can specify what jar they want from jenkins as well by doing [num] at end.

**Comment by NewAmazingPVP** [comment]
Hey @Kaerix Are you able to test this [build](https://cdn.discordapp.com/attachments/1103725182314614834/1250097881017483315/autoupdateplugins-jenkinsMultiArtifact.jar?ex=6669b3e0&is=66686260&hm=41de7515db71ceb2cb7bbba069a8dab5c03d161b61010a3d26e19f673d31b49d&) I have added the Jenkins multi artifact support. Also, now for multi-artifacts, you don't have to do multi[num]; you just need [num] at the end. Please let me know if there are any issues.

**Comment by Kaerix** [comment]
Also, one caveat I think could be an issue is for example, when I want to download AuthMeVelocity from Modrinth. I need the Paper version of the plugin. But the Modrinth page hosts both types (Velocity and Paper) of the plugin on one page. Does your plugin distinguish between those or only the latest will be downloaded?

**Comment by NewAmazingPVP** [comment]
It's great to hear it's working! Also, for Modrinth, I did realize that caveat and have already implemented auto-platform checking and it will download the right platform builds, but I'm glad that you found that out and informed me.
